### PR TITLE
Adding some useful utility tiles

### PR DESCRIPTION
**Pull request by riknoll**
Adding some tiles to the miscellaneous category.
Screen Shot 2020-04-23 at 11 13 12 AM

### CODE REVIEW

**Comment by riknoll** [comment]
If anyone has any other ideas for tiles, let me know and I'll add them. I haven't "tested" this, because it needs to be merged before I can import it into the editor.

**Comment by shakao** [comment]
should we put them in a separate category? like "placeholder" (but a better name) or something? it does seem a little different from the rocks/buttons/etc in misc

**Comment by riknoll** [comment]
I'm thinking, maybe some tiles that just have the numbers 1-9? And maybe some icon tiles, like heart, question mark, etc.

**Comment by riknoll** [comment]
I would love to but we hardcoded the tilemap editor categories

**Comment by shakao** [comment]
.......... right. yes. argh.

**Comment by shakao** [comment]
yeah maybe like, heart, triangle, circle, square.... question mark, exclamation point.... asterisk? and i like the number ones as well. maybe one that's just zebra stripes?

**Comment by shakao** [comment]
could we sell "extra tilemap category" as a point fix?

**Comment by riknoll** [comment]
I'll make a PR and if it's small enough we can try to sell it

**Comment by darzu** [comment]
With that other PR, can these placeholders be an extension?

I agree some symbols and icons would be useful.

I wonder if one of the four colors could be transparent? That would be useful in situations where users specify a background color or image themselves (e.g. 2cat2curious)

Awesome set so far however!

**Comment by riknoll** [comment]
They might be pretty difficult to read on a transparent background with the checkerboard behind it.

I can make it a separate extension, but I would prefer it to come with pxt-tilemaps. It's very easy to ignore if you don't want it and I don't think it's useful without the tilemaps extension. Also, I don't want to flood the extensions dialog.

**Comment by shakao** [comment]
ship it!!

**Comment by darzu** [comment]
Hmm they're all in the "Miscelanous" category. How do we move them to their own category?
image

**Comment by darzu** [comment]
Woot! Fixed it. Looks fantastic:
image

**Pull request merged**
